### ISSUE TITLE
Train button is unavailable

### ISSUE THREAD

**Issue by byrongamatos** [viktorvano/SpeechRecognitionAI#17]
Hello, I have recorded 77 samples (11 phrases, 7 times each), but the Train button on Train AI is disabled. What are the prerequisites to enable it?

**Comment by viktorvano** [comment]
How did you configure the topology?
Needs probably more layers. (min 3 layers, but recommend 5 hidden layers)
It needs equal count of words and multiple layers of neurons.

buttonTrain.setDisable(!goodWordCount || topology.size() < 3);

Count words function:
https://github.com/viktorvano/SpeechRecognitionAI/blob/master/src/com/ViktorVano/SpeechRecognitionAI/GUI/SpeechRecognitionAI.java#L1522

**Comment by byrongamatos** [comment]
Im a complete novice to the terminology so apologies.

If I compare the documentation screenshots, the difference is that indeed the topology is empty, but I don't have any button to add it. Must it be somehow generated?

![image](https://user-images.githubusercontent.com/9028385/202177513-02560632-15f7-43c0-8313-a7103c24c3a4.png)

**Comment by viktorvano** [comment]
Just type there a number like 80, click Add Hidden layer, then a smaller number, click Add...
So the topology of hidden layers can be like 80, 75, 60, 50, 40.
Deeper hidden layers create like abstraction or a meaning of an input. That's why multiple hidden layers.

**Comment by byrongamatos** [comment]
Thank you, I am able to start the training now.

**Comment by viktorvano** [comment]
You are welcome.
